title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
url: https://graphicasso.github.io/gpd-test2

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
